#!/usr/bin/env python3
"""Generate GBC note period lookup tables.

GBC period formula:
  Square channels: f_Hz = 131072 / (2048 - x)
  Wave channel:    f_Hz =  65536 / (2048 - x)   (octave lower than square)

We generate 60 notes (5 octaves: C-2 .. B-6) for the SQUARE table.
A separate WAVE table reuses the same musical pitches by halving the
real frequency target (so the wave channel sounds the same musical note
as a square channel at the same note index).
"""

import sys
from pathlib import Path

NOTE_NAMES = ['C-', 'C#', 'D-', 'D#', 'E-', 'F-',
              'F#', 'G-', 'G#', 'A-', 'A#', 'B-']

def freq_of(note_index):
    # note_index 0 = C-2 (semitone-wise: 12*2 = 24 semitones below A4? no)
    # A4 = 440 Hz, A4 in our table sits at octave 4, semitone 9.
    # offset_from_a4 = (octave - 4) * 12 + (semitone - 9)
    octave = 2 + note_index // 12
    semi = note_index % 12
    offset = (octave - 4) * 12 + (semi - 9)
    return 440.0 * (2.0 ** (offset / 12.0))


def period_square(f):
    # x such that f = 131072 / (2048 - x)
    x = 2048 - 131072 / f
    x = round(x)
    return max(0, min(2047, x))


def period_wave(f):
    # f = 65536 / (2048 - x)
    x = 2048 - 65536 / f
    x = round(x)
    return max(0, min(2047, x))


def main():
    out_path = Path(sys.argv[1] if len(sys.argv) > 1 else 'src/notes.asm')
    n_notes = 60  # C-2 .. B-6
    sq_periods = [period_square(freq_of(i)) for i in range(n_notes)]
    wv_periods = [period_wave(freq_of(i)) for i in range(n_notes)]

    lines = []
    lines.append('; Auto-generated by tools/gen_notes.py — do not edit by hand.')
    lines.append('SECTION "NoteTables", ROM0')
    lines.append('')
    lines.append('; Square channel period values (lo byte, then hi byte interleaved)')
    lines.append('NotePeriodsSquare::')
    for i, x in enumerate(sq_periods):
        octave = 2 + i // 12
        name = NOTE_NAMES[i % 12]
        lo = x & 0xFF
        hi = (x >> 8) & 0x07
        lines.append(f'    DB ${lo:02X}, ${hi:02X}  ; ${i:02X} {name}{octave}  x={x}  f={freq_of(i):.2f}Hz')
    lines.append('NotePeriodsSquare_End::')
    lines.append('')
    lines.append('; Wave channel period values')
    lines.append('NotePeriodsWave::')
    for i, x in enumerate(wv_periods):
        octave = 2 + i // 12
        name = NOTE_NAMES[i % 12]
        lo = x & 0xFF
        hi = (x >> 8) & 0x07
        lines.append(f'    DB ${lo:02X}, ${hi:02X}  ; ${i:02X} {name}{octave}  x={x}  f={freq_of(i):.2f}Hz')
    lines.append('NotePeriodsWave_End::')
    out_path.write_text('\n'.join(lines) + '\n', encoding='utf-8')
    print(f'Wrote {out_path}')


if __name__ == '__main__':
    main()
